<a href="https://colab.research.google.com/github/Seema44/hello-world/blob/master/Functions_num.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr_1=np.array([1,2,3,4])

In [ ]:
arr_1

array([1, 2, 3, 4])

In [ ]:
print(arr_1)

[1 2 3 4]


In [ ]:
type(arr_1)

numpy.ndarray

In [ ]:
arr_1.ndim

1

In [ ]:
arr_2=np.array([[1,2,3,4],[5,6,7,8]])
arr_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
type(arr_2)

numpy.ndarray

In [ ]:
arr_2.ndim

2

In [ ]:
arr_1.size


4

In [ ]:
arr_2.size

8

In [ ]:
arr_1.shape


(4,)

In [ ]:
arr_2.shape


(2, 4)

In [ ]:
# (row,col)

In [ ]:
arr_1.dtype


dtype('int64')

In [ ]:
arr_2.dtype

dtype('int64')

In [ ]:
mat_ones= np.array([[1,1,1],[1,1,1],[1,1,1]])

In [ ]:
print(mat_ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
mx_1s=np.ones(5)

In [ ]:
mx_1s

array([1., 1., 1., 1., 1.])

In [ ]:
mx_1s.dtype



dtype('float64')

In [ ]:
mx_1s=np.ones((3,3))

In [ ]:
mx_1s

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:


mx_1s=np.ones((2,5),dtype=bool,order='c')

In [ ]:
mx_1s

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:


mx_1s=np.ones((2,5),dtype=int,order='c')


In [ ]:
print((mx_1s))


[[1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
  mx_0s=np.zeros((3,4),dtype=int)

In [ ]:
mx_0s


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
  mx_0s=np.zeros((3,4),dtype=str)

In [ ]:
mx_0s

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [ ]:
  print(bool(mx_0s))

ValueError: ignored

In [ ]:
en=''

In [ ]:
print(bool(en))

False


In [ ]:
mx_em=np.empty((3,5),dtype=int)

In [ ]:
mx_em

array([[           80735616,                  78,                   0,
                          0,                   0],
       [8319683848551211643, 3180222411935070754, 8391722768137527840,
        7959390389040738153, 2318284202865992308],
       [8675445202132104482, 7957695011165139568, 2318365875964093043,
        7233184988217307170,     137839914269218]])

# New Section

In [ ]:
arr_1=np.arange(1,13)

In [ ]:
print(arr_1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
arr_1=np.arange(1,13,2)

In [ ]:
print(arr_1)

[ 1  3  5  7  9 11]


In [ ]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [ ]:
arr_2=arr_1.reshape(2,3)

In [ ]:
arr_2           


array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [ ]:
arr_3=arr_1.reshape(2,3,2)

In [ ]:
arr_3


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
arr=np.arange(1,25).reshape(3,8)

In [ ]:
arr


array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.flatten(order='F')

array([ 1,  9, 17,  2, 10, 18,  3, 11, 19,  4, 12, 20,  5, 13, 21,  6, 14,
       22,  7, 15, 23,  8, 16, 24])

In [ ]:
arr.transpose()

array([[ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23],
       [ 8, 16, 24]])

# New Section